version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: fullcycle
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pfullcycle"]
      interval: 5s
      timeout: 20s
      retries: 10

  nodejs:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
